cli:
  app_directory: apps
  base_model: apps.teams.models.BaseTeamModel
  css_framework: tailwind
  module_path: apps
  template_directory: templates
  use_teams: true
default_context:
  _pegasus_version: 2025.6.2
  author_name: Abdulelah alnaddaf
  bundler: vite
  ci: github_actions
  css_framework: tailwind
  css_theme: default
  database: postgres
  deploy_platform: none
  description: The most amazing SaaS application the world has ever seen
  docker_setup: default
  domain_name: localhost:8000
  email: adh.ndf@gmail.com
  enable_github_login: y
  enable_google_login: y
  enable_twitter_login: y
  front_end_framework: htmx
  github_username: abdulelah776
  include_static_files: n
  marketing_email_platform: email_octopus
  plugins:
  - group_chat
  post_process: y
  project_name: Tokra Admin Panel
  project_slug: tokra_loop_admin
  python_package_manager: uv
  standalone_front_end: none
  stripe_payment_mode: checkout
  subscription_billing_model: default
  subscription_pricing_ui: in_app
  use_2fa: y
  use_admin_docs: n
  use_ai_rules_claude: y
  use_ai_rules_cursor: n
  use_ai_rules_junie: n
  use_api_auth: n
  use_api_keys: y
  use_async: y
  use_celery: y
  use_cloud_media_storage: y
  use_dark_mode: y
  use_debug_toolbar: n
  use_docker: y
  use_ecommerce_example: n
  use_examples: y
  use_flowbite: y
  use_health_checks: n
  use_impersonation: y
  use_sentry: n
  use_shadcn: y
  use_subscriptions: y
  use_teams: y
  use_teams_example: n
  use_translations: y
  use_wagtail: n
